# TASK 1

In [1]:
import numpy as np

In [2]:
array =  np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
array2d = np.arange(1,10).reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [5]:
type(arr)

numpy.ndarray

# TASK 2

In [8]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
print(A)
print(B)

[10 20 30 40]
[1 2 3 4]


In [9]:
print( A+ B)

[11 22 33 44]


In [10]:
print(A-B)

[ 9 18 27 36]


In [11]:
print(A*B)

[ 10  40  90 160]


In [12]:
print(A/B)

[10. 10. 10. 10.]


In [14]:
print(A ** 2)

[ 100  400  900 1600]


In [15]:
print(B ** 2)

[ 1  4  9 16]


# TASK 3

In [17]:
values = np.array([2,4,6,8,10])
print(values)


[ 2  4  6  8 10]


In [18]:
np.sqrt(values)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [19]:
np.exp(values)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

In [20]:
np.log(values)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

In [21]:
np.sum(values)

np.int64(30)

In [22]:
np.cumsum(values)

array([ 2,  6, 12, 20, 30])

# TASK 4

In [23]:
data = np.array([[10,20,30],[40,50,60],[70,80,90]])
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
np.sum(data, axis=1)

array([ 60, 150, 240])

In [27]:
np.sum(data, axis=0)

array([120, 150, 180])

In [28]:
np.min(data)

np.int64(10)

In [29]:
np.max(data)

np.int64(90)

In [30]:
np.mean(data)

np.float64(50.0)

# TASK 5

In [32]:
marks = np.array([78,85,90,66,72,88,95,60])
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [35]:
print(np.mean(marks))

79.25


In [36]:
print(np.median(marks))

81.5


In [37]:
print(np.var(marks))

134.1875


In [38]:
print(np.std(marks))

11.583932838203095


In [39]:
print(np.min(marks))

60


In [40]:
print(np.max(marks))

95


In [41]:
print(np.max(marks) - np.min(marks))

35


# TASK 6

In [43]:
np.sort(marks)

array([60, 66, 72, 78, 85, 88, 90, 95])

In [44]:
np.percentile(marks, 25)

np.float64(70.5)

In [45]:
np.percentile(marks, 50)

np.float64(81.5)

In [47]:
np.percentile(marks, 75)

np.float64(88.5)

In [50]:
avg = np.average(marks)
avg

np.float64(79.25)

In [ ]:
count = 0
for i in marks:
    if i > avg:
        count += 1
print(count)

4


# TASK 7

In [52]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
sales

array([1200, 1500,  900, 2000, 1800, 1700, 1600])

In [53]:
np.sum(sales)

np.int64(10700)

In [55]:
np.average(sales)

np.float64(1528.5714285714287)

In [56]:
np.max(sales)

np.int64(2000)

In [57]:
np.min(sales)

np.int64(900)

In [58]:
np.std(sales)

np.float64(345.2298849598449)

In [59]:
avg = np.average(sales)
avg

np.float64(1528.5714285714287)

In [61]:
count = 0
for i in sales:
    if i > avg:
        count += 1
print(count)

4
