# Numpy

#### Numpy is a Fundamental Package for scientific computing in python . It is a Python Librarythat provides a Multi Dimenstional Array object and various derived objects such as Masked Arraysor Matrices and an assortment of routines for fast operations on Arrays including Mathematical ,Logical , Shape Manipulation , Sorting , Selecting , I/0 , Discrete Fourier Transform , BasicLinear Algebra , Stastical Operations , Random Simulation , etc .

#### At the core of the Numpy Package is the ndimensional Array object

## -> Why Numpy?

## -> 2008-200, Data Science ---> Matlab, R Language

## -> Data Types in python like ---> List, Dictionaries are slow

## -> Syntax of the python is very easy

## -> We need Speed and Less Memory to work with the huge amount of data.

## -> Numpy ---> created in C language and ---> Wrapped in the python language

## -> Numpy ---> syntax easy ---> simple=y performs scientific calculations ---> creates multi dimensional arrays -----> Speedy and faster ---> Less Memory

### Libraries like scikit learn, Tensorflow and pytorch require input data in numpy arrays or tensors



## Numpy Arrays Vs Python Sequences

#### Numpy arrays have a fixed size at creation, unlike python lists which grows dynamically

## Changingthw size of an ndim array will create a new array and delete the original

#### The elements in a Numpy Array are required to be of the same data types (no mixed datatypes) and thus will be of the same size in memory.

#### Numpy Arrays facilitate advanced mathematical and other types of operations on large number of data typically that operations are executed more efficiently on less code by using the python built in sequence libraries


In [2]:
pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

## 1. np.array()
#### Creation of numpy array

In [6]:
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

In [7]:
print(numpy_array)

[1 2 3 4 5]


In [ ]:
type(numpy_array) # vector

numpy.ndarray

In [11]:
two_d_array = np.array([[1,2,3],[4,5,6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(two_d_array) # matrix

numpy.ndarray

In [15]:
Three_D_Array = np.array([[[1,2],[2,5]],[[5,6],[8,7]],[[5,4],[9,5]]])
Three_D_Array

array([[[1, 2],
        [2, 5]],

       [[5, 6],
        [8, 7]],

       [[5, 4],
        [9, 5]]])

In [16]:
print(Three_D_Array)

[[[1 2]
  [2 5]]

 [[5 6]
  [8 7]]

 [[5 4]
  [9 5]]]


In [17]:
type(Three_D_Array) # Tensors

numpy.ndarray

## dtype parameter ----> Which can help us out with deciding about the size of the data that we are going to store inside our array

In [18]:
np.array([1,2,3,4,5], dtype = np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [19]:
np.array([1,2,3,4,5], dtype = np.int64)

array([1, 2, 3, 4, 5])

In [20]:
np.array([1,5,8,9],dtype = float)

array([1., 5., 8., 9.])

In [23]:
np.array([1,5,8,0],dtype = bool)

array([ True,  True,  True, False])

### range() ----> for i in range()

### 

In [25]:
list1 = []
for i in range(16):
    list1.append(i)
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [26]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## 2. arange() ---- > It helps us out with providing the values over a certain range

In [27]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [28]:
np.arange(5,21,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arange_data = np.arange(1,17)

## 3. np.reshape() --- > It helps us out with changing the shape of the array as
per our needs

In [35]:
arange_data.reshape(4,4) # rows,columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
np.arange(2,17,2).reshape(2,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

## 4. ones() function

#### Useful in neural network architecture, connecting the nuerons for initialising the weight with value as one

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 5. Zeros() function

In [41]:
np.zeros((4,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## 6. random() --- > It helps us out with generating anyrandom values from 0 to 1 inside our matrix

In [46]:
np.random.random((3,4))

array([[0.33065552, 0.15728067, 0.72937775, 0.71453247],
       [0.6715601 , 0.36958563, 0.49845155, 0.98151651],
       [0.64153817, 0.92524256, 0.56479773, 0.39224528]])

## 7. Identity() --- > It helps us out with creating the matrix as an Identity Matrix

In [52]:
np.identity((3),dtype  = int) # only for square matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 8. linspace()

#### linspace() --- > it makes sure that every value with the given range is going to have similar distance from each other

In [53]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])