# Numpy

#### Numpy is a Fundamental Package for scientific computing in python . It is a Python Librarythat provides a Multi Dimenstional Array object and various derived objects such as Masked Arraysor Matrices and an assortment of routines for fast operations on Arrays including Mathematical ,Logical , Shape Manipulation , Sorting , Selecting , I/0 , Discrete Fourier Transform , BasicLinear Algebra , Stastical Operations , Random Simulation , etc .

#### At the core of the Numpy Package is the ndimensional Array object

## -> Why Numpy?

## -> 2008-200, Data Science ---> Matlab, R Language

## -> Data Types in python like ---> List, Dictionaries are slow

## -> Syntax of the python is very easy

## -> We need Speed and Less Memory to work with the huge amount of data.

## -> Numpy ---> created in C language and ---> Wrapped in the python language

## -> Numpy ---> syntax easy ---> simple=y performs scientific calculations ---> creates multi dimensional arrays -----> Speedy and faster ---> Less Memory

### Libraries like scikit learn, Tensorflow and pytorch require input data in numpy arrays or tensors



## Numpy Arrays Vs Python Sequences

#### Numpy arrays have a fixed size at creation, unlike python lists which grows dynamically

## Changingthw size of an ndim array will create a new array and delete the original

#### The elements in a Numpy Array are required to be of the same data types (no mixed datatypes) and thus will be of the same size in memory.

#### Numpy Arrays facilitate advanced mathematical and other types of operations on large number of data typically that operations are executed more efficiently on less code by using the python built in sequence libraries


In [358]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [359]:
import numpy as np

## 1. np.array()
#### Creation of numpy array

In [360]:
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

In [361]:
print(numpy_array)

[1 2 3 4 5]


In [362]:
type(numpy_array) # vector

numpy.ndarray

In [363]:
two_d_array = np.array([[1,2,3],[4,5,6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [364]:
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [365]:
type(two_d_array) # matrix

numpy.ndarray

In [366]:
Three_D_Array = np.array([[[1,2],[2,5]],[[5,6],[8,7]],[[5,4],[9,5]]])
Three_D_Array

array([[[1, 2],
        [2, 5]],

       [[5, 6],
        [8, 7]],

       [[5, 4],
        [9, 5]]])

In [367]:
print(Three_D_Array)

[[[1 2]
  [2 5]]

 [[5 6]
  [8 7]]

 [[5 4]
  [9 5]]]


In [368]:
type(Three_D_Array) # Tensors

numpy.ndarray

## dtype parameter ----> Which can help us out with deciding about the size of the data that we are going to store inside our array

In [369]:
np.array([1,2,3,4,5], dtype = np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [370]:
np.array([1,2,3,4,5], dtype = np.int64)

array([1, 2, 3, 4, 5])

In [371]:
np.array([1,5,8,9],dtype = float)

array([1., 5., 8., 9.])

In [372]:
np.array([1,5,8,0],dtype = bool)

array([ True,  True,  True, False])

### range() ----> for i in range()

### 

In [373]:
list1 = []
for i in range(16):
    list1.append(i)
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [374]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## 2. arange() ---- > It helps us out with providing the values over a certain range

In [375]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [376]:
np.arange(5,21,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [377]:
arange_data = np.arange(1,17)

## 3. np.reshape() --- > It helps us out with changing the shape of the array as
per our needs

In [378]:
arange_data.reshape(4,4) # rows,columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [379]:
np.arange(2,17,2).reshape(2,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

## 4. ones() function

#### Useful in neural network architecture, connecting the nuerons for initialising the weight with value as one

In [380]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 5. Zeros() function

In [381]:
np.zeros((4,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## 6. random() --- > It helps us out with generating anyrandom values from 0 to 1 inside our matrix

In [382]:
np.random.random((3,4))

array([[0.33976765, 0.8003376 , 0.28428271, 0.45166266],
       [0.95567641, 0.93455086, 0.93619993, 0.56841206],
       [0.95014269, 0.77105439, 0.74087248, 0.93983142]])

## 7. Identity() --- > It helps us out with creating the matrix as an Identity Matrix

In [383]:
np.identity((3),dtype  = int) # only for square matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 8. linspace()

#### linspace() --- > it makes sure that every value with the given range is going to have similar distance from each other

In [384]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Attributes

## 1. ndim
### ndim stands for the n dimensions

In [385]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [386]:
arr.ndim

1

In [387]:
arr3 = np.array([[[1,2],[2,5]],[[5,6],[8,7]],[[5,4],[9,5]]])
arr3

array([[[1, 2],
        [2, 5]],

       [[5, 6],
        [8, 7]],

       [[5, 4],
        [9, 5]]])

In [388]:
arr3.ndim # 3 dimensional array

3

## 2. shape 
### It provides us with the idea about the rows, columns in our dataset or in array

In [389]:
array =np.array([[1,2,3],[1,2,4],[1,2,5]])
array


array([[1, 2, 3],
       [1, 2, 4],
       [1, 2, 5]])

In [390]:
array.shape

(3, 3)

## 3. size

### Tells us how many total no : of elements in side the array or dataset

In [391]:
count = np.arange(5,57)
count.size

52

## 4. itemsize

### provides with the idea about the size of aunique element inside our array in bytes

In [392]:
np.array([[1,2],[2,3]], dtype = np.int32).itemsize

4

## 5. dtype

### Provides us with the idea about the type of every item inside our array

In [393]:
print(np.array([1,2,3]).dtype) #8 bytes

int64


## astype() -- function

### astype() will be helping us out with figuring out the data type of the column in dataset in pandas and it will be used in numpy as well for getting the datatype change of our overall array

In [394]:
array4 = np.arange(1,10).reshape(3,3)
array4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [395]:
array4.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [396]:
type(array4)

numpy.ndarray

In [397]:
array4.dtype

dtype('int64')

In [398]:
array = array4.astype('float64')

In [399]:
array.dtype

dtype('float64')

## Mathematical Operations in Numpy

### Scalar Operations

#### ---> Here a scalar value will be multiplied with the array (scalar multiplication)

In [411]:
array = np.random.random((3,3)) * 100
array

array([[19.41233445, 16.33606509, 11.14156661],
       [38.63414803, 52.15816476, 85.34984776],
       [56.93216888, 37.23400204, 88.212815  ]])

In [412]:
np.round(array) # round off function

array([[19., 16., 11.],
       [39., 52., 85.],
       [57., 37., 88.]])

In [413]:
array = array.astype('int32')

In [414]:
array

array([[19, 16, 11],
       [38, 52, 85],
       [56, 37, 88]], dtype=int32)

## Scalar Operation With our Matrix or Array

In [415]:
array+2

array([[21, 18, 13],
       [40, 54, 87],
       [58, 39, 90]], dtype=int32)

In [416]:
array-10

array([[ 9,  6,  1],
       [28, 42, 75],
       [46, 27, 78]], dtype=int32)

In [417]:
array*2

array([[ 38,  32,  22],
       [ 76, 104, 170],
       [112,  74, 176]], dtype=int32)

In [418]:
# array/2

#### We can apply scalar operations with the arrayin terms of arthimetic operations

### Testing with relational operations


In [419]:
array>60

array([[False, False, False],
       [False, False,  True],
       [False, False,  True]])

## Vector Operations

### ---> Operations will be between the matrices

In [423]:
arr_1 = np.arange(1,17).reshape(4,4)


In [424]:
arr_2 = np.arange(17,33).reshape(4,4)

In [425]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [426]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [427]:
arr_1+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [428]:
arr_2 - arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [429]:
arr_1 * arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

#### Important Functions in Numpy for Machine Learning and Data Science

## for Matrix and normal array also

## 1. max()

In [433]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [435]:
max = np.max(arr_1)
print(max)

16


In [436]:
array_data = np.round(np.random.random((4,4)) * 100).astype('int32')

In [437]:
array_data

array([[19,  7, 40, 91],
       [93,  2, 99, 61],
       [58, 25, 19, 64],
       [46, 11, 24, 52]], dtype=int32)

### axis --- > it provides us with the idea about the anyoperation value inside a speciic row or column or wecan get a specific value row wise or column wise

### axix = 0 --> column wise operation

### axis = 1 --> row wise operation 

In [438]:
np.max(array_data,axis = 0)

array([93, 25, 99, 91], dtype=int32)

In [439]:
np.max(array_data,axis = 1)

array([91, 99, 64, 52], dtype=int32)

## 2. min()

In [440]:
np.min(array_data)

np.int32(2)

In [441]:
np.min(array_data, axis = 0)

array([19,  2, 19, 52], dtype=int32)

In [442]:
np.min(array_data, axis = 1)

array([ 7,  2, 19, 11], dtype=int32)

In [444]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [445]:
np.max(array)

np.int64(9)

In [446]:
np.min(array)

np.int64(1)

## 3. sum()

In [447]:
np.sum(array)

np.int64(45)

In [448]:
np.sum(array_data)

np.int64(711)

In [449]:
np.sum(array_data, axis = 1)

array([157, 255, 166, 133])

In [450]:
np.sum(array_data, axis = 0)

array([216,  45, 182, 268])

## 4. product()

In [452]:
np.prod(array)

np.int64(362880)

In [453]:
np.prod(array_data)

np.int64(-442573715383123968)

In [454]:
np.prod(array_data, axis = 1)

array([ 484120, 1123254, 1763200,  631488])

In [455]:
np.prod(array_data, axis = 0)

array([ 4714356,     3850,  1805760, 18473728])