# Numpy

In [1]:
import numpy as np

In [3]:
arr_for_log = np.array([1, np.e, 100])
arr_for_log


array([  1.        ,   2.71828183, 100.        ])

In [4]:
np.log(arr_for_log)

array([0.        , 1.        , 4.60517019])

In [5]:
np.log2(arr_for_log)

array([0.        , 1.44269504, 6.64385619])

In [6]:
np.log10(arr_for_log)

array([0.        , 0.43429448, 2.        ])

In [7]:
arr = np.array([1,2,3,4,5,6])
np.power(arr,2)

array([ 1,  4,  9, 16, 25, 36])

In [8]:
np.exp([1,2,3,4,5,6])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 2])

print("np.less(a, b):", np.less(a, b))
print("np.greater_equal(a, b):", np.greater_equal(a, b))
print("np.equal(a, b):", np.equal(a, b))
print("np.not_equal(a, b):", np.not_equal(a, b))

np.less(a, b): [ True False False False]
np.greater_equal(a, b): [False  True  True  True]
np.equal(a, b): [False  True False False]
np.not_equal(a, b): [ True False  True  True]


In [10]:
#
# 10. STATISTICAL & AGGREGATION FUNCTIONS
#

stats_arr = np.array([[1, 2, 3],
[4,5,6],
[7,8,9]])

print("Array: \n", stats_arr)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print("\nSum of all elements:", np.sum(stats_arr))
print("Mean:", np.mean(stats_arr))
print("Standard Deviation:", np.std(stats_arr))
print("Variance:", np.var(stats_arr))


Sum of all elements: 45
Mean: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667


#### arg give index

In [12]:
print("\nMin:", np.min(stats_arr))
print("Max:", np.max(stats_arr))
print("Argmin (index of min):", np.argmin(stats_arr))
print("Argmax (index of max):", np.argmax(stats_arr))


Min: 1
Max: 9
Argmin (index of min): 0
Argmax (index of max): 8


In [13]:
#
# 11. BROADCASTING EXAMPLES
#

# Example 1: Adding a scalar to an array
arr_b = np.array([1, 2, 3])
print("Original array:", arr_b)
print("Add 10 to each element:", arr_b + 10)

Original array: [1 2 3]
Add 10 to each element: [11 12 13]


In [17]:
# Example 2: Broad[casting two arrays of compatible shapes
mat_b1 = np.array([[1], [2], [3]]) # shape (3,1)
mat_b2 = np.array([10, 20, 30])

print("\nBroadcasting shapes (3,1) and (3,) in an operation:")
print("mat_b1 + mat_b2:\n", mat_b1 + mat_b2)



Broadcasting shapes (3,1) and (3,) in an operation:
mat_b1 + mat_b2:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [22]:
# 12. LINEAR ALGEBRA EXAMPLES
#

# Create a 2D matrix
A = np. array([[1, 2],
[3,4]])

B = np. array([[2, 0],
[1, 2]])

In [24]:
np.matmul(A,B)

array([[ 4,  4],
       [10,  8]])

In [23]:
# 12.2 Matrix inversion & determinant
inv_A = np.linalg.inv(A)
det_A = np.linalg.det(A)

print("\nInverse of A:\n", inv_A)
print("Determinant of A:", det_A)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
