<div align="center">

# 🧠✨ TENSORS IN MACHINE LEARNING
## From Scalars to 5D Data

### NumPy • TensorFlow • Computer Vision • NLP • Deep Learning

</div>

<div style="padding:18px;border-radius:14px;border:2px solid #4c78a8">

### 🎯 Big Idea

A **tensor is a multidimensional numerical data structure** used throughout modern machine learning and deep learning.

Think of it as a generalization of:

**scalar → vector → matrix → higher-dimensional array**

</div>

---

## 🗺️ What this notebook covers

```text
0D  → Scalar
1D  → Vector
2D  → Matrix
3D  → Volume / Image
4D  → Batch of images
5D  → Video / sequence batch

        ↓

NumPy arrays
        ↓
TensorFlow tensors
        ↓
CNN / RNN / LSTM / NLP / Computer Vision
```

> **Important:** In ML, people often use “dimension”, “axis”, “rank”, and “shape” loosely. They are related but not identical. This notebook keeps the terminology precise.

# 🌟 1. What is a Tensor?

A **tensor** is an n-dimensional array of numerical values.

Examples:

```text
7
        → 0D tensor / scalar

[1, 2, 3, 4]
        → 1D tensor / vector

[1 2 3]
[4 5 6]
        → 2D tensor / matrix

multiple matrices
        → 3D tensor

multiple 3D tensors
        → 4D tensor
```

### Why tensors matter

Machine learning models work with numerical data.

A tensor provides a structured way to represent:

- numerical features,
- tables,
- images,
- batches of images,
- text representations,
- audio,
- video,
- neural-network activations,
- model weights.

### 🧩 Tensor terminology

| Term | Meaning |
|---|---|
| **Scalar** | A single value |
| **Vector** | A 1D array |
| **Matrix** | A 2D array |
| **Tensor** | General n-dimensional array |
| **Rank / number of axes** | Number of dimensions/axes |
| **Shape** | Size along each axis |

For example:

```python
x.shape == (32, 224, 224, 3)
```

means:

```text
32  → batch size
224 → height
224 → width
3   → RGB channels
```

This tensor has **4 axes**.

# 👀 2. Tensor Dimensions at a Glance

![Tensor dimensions](assets/tensor_dimensions.png)

### Quick memory table

| Order | Common name | Example |
|---:|---|---|
| 0D | Scalar | `7` |
| 1D | Vector | `[1, 2, 3]` |
| 2D | Matrix | rows × columns |
| 3D | Tensor / volume | height × width × channels |
| 4D | Batch tensor | batch × height × width × channels |
| 5D | Video batch tensor | batch × time × height × width × channels |

> **Exam tip:** If asked “What is a tensor?”, first define it as a multidimensional array and then give 0D–5D examples.

# 0️⃣ 3. 0D Tensor — Scalar

A **0D tensor** contains a single numerical value.

```text
7
```

It has:

```text
shape = ()
rank  = 0
```

### Examples

- Loss value
- Learning rate
- Temperature
- A single measurement
- A single prediction score

### NumPy

```python
import numpy as np

x = np.array(7)

print(x)
print(x.ndim)
print(x.shape)
```

Expected:

```text
7
0
()
```

### 🧠 Visual

```text
┌─────┐
│  7  │
└─────┘
 Scalar
```

In [ ]:
import numpy as np

scalar = np.array(7)

print("Value :", scalar)
print("Rank  :", scalar.ndim)
print("Shape :", scalar.shape)

# 1️⃣ 4. 1D Tensor — Vector

A **1D tensor** stores values along one axis.

Example:

```text
[1, 2, 3, 5]
```

```text
shape = (4,)
rank  = 1
```

It can represent:

- a single row of features,
- a list of measurements,
- a sequence of values,
- an embedding vector.

### Example

Suppose a student has four features:

```text
[CGPA, attendance, projects, internships]

[8.5, 90, 3, 2]
```

This is a 1D vector.

### Important distinction

A vector is **one-dimensional in array structure**, even though we may informally draw it horizontally or vertically.

In [ ]:
vector = np.array([1, 2, 3, 5])

print("Vector :", vector)
print("Rank   :", vector.ndim)
print("Shape  :", vector.shape)

# 2️⃣ 5. 2D Tensor — Matrix

A **2D tensor** has two axes:

```text
rows × columns
```

Example:

```text
[1 2 3]
[4 5 6]
[7 8 9]
```

Shape:

```text
(3, 3)
```

### Common ML example — tabular dataset

```text
           age  salary  score
Person 1    20   30000     80
Person 2    22   35000     85
Person 3    24   40000     90
```

This can be represented as a 2D array:

```text
samples × features
```

For example:

```text
(3, 3)
```

### 🔑 Memory trick

```text
2D = rows + columns
```

Matrices are fundamental in:

- linear algebra,
- tabular data,
- neural-network computations,
- transformations,
- weight matrices.

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)
print("Rank  :", matrix.ndim)
print("Shape :", matrix.shape)

# 🖼️ 6. 3D Tensor — Images and Multiple Matrices

A **3D tensor** can be understood as a stack of 2D matrices.

![3D tensor](assets/3d_tensor.png)

For an RGB image, a common representation is:

```text
Height × Width × Channels
```

Example:

```text
224 × 224 × 3
```

where:

```text
224 → height
224 → width
3   → RGB channels
```

### 🎨 RGB channels

An RGB image contains three channels:

```text
R → Red
G → Green
B → Blue
```

Each pixel can be represented by three values.

For example:

```text
Pixel = [255, 0, 0]
          │   │  │
          R   G  B

        = Red
```

### Why 3D?

Think of it as three 2D matrices:

```text
Red channel    Green channel    Blue channel
┌─────────┐    ┌─────────┐      ┌─────────┐
│ values  │    │ values  │      │ values  │
│ values  │    │ values  │      │ values  │
└─────────┘    └─────────┘      └─────────┘

        Combined → RGB image
```

## 🌈 RGB image visualization

![RGB tensor](assets/rgb_image_tensor.png)

A colored image is therefore not just “a picture” to a neural network.

It is numerical data arranged along several axes.

In [ ]:
# Create a small RGB image-like tensor

rgb = np.zeros((4, 5, 3), dtype=np.uint8)

# Set one pixel to red
rgb[0, 0] = [255, 0, 0]

print("Shape:", rgb.shape)
print("Rank :", rgb.ndim)
print("Pixel [0, 0]:", rgb[0, 0])

# 🧮 7. NumPy Arrays as Tensors

In Python, **NumPy arrays** are commonly used to represent numerical tensors.

```text
Python list
    ↓
np.array()
    ↓
NumPy ndarray
    ↓
numerical tensor-like structure
```

### Example

```python
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

Properties:

```python
x.ndim     # number of axes
x.shape    # size of each axis
x.size     # total number of elements
x.dtype    # data type
```

### 🔍 Important

For a tensor with shape:

```text
(2, 3, 4)
```

the number of elements is:

```text
2 × 3 × 4 = 24
```

In [ ]:
x = np.zeros((2, 3, 4))

print("ndim :", x.ndim)
print("shape:", x.shape)
print("size :", x.size)
print("dtype:", x.dtype)

# 4️⃣ 8. 4D Tensor — Batch of Images

A single RGB image is commonly:

```text
H × W × C
```

For example:

```text
224 × 224 × 3
```

But neural networks normally process **multiple images together**.

Add a batch axis:

```text
N × H × W × C
```

Example:

```text
32 × 224 × 224 × 3
```

where:

```text
32  → number of images
224 → height
224 → width
3   → RGB channels
```

![4D tensor](assets/4d_tensor.png)

### 🧠 Think of it as

```text
Image 1 → 3D tensor
Image 2 → 3D tensor
Image 3 → 3D tensor
...
Image 32 → 3D tensor

        ↓ stack along batch axis

      4D tensor
```

This is extremely common in **CNN-based computer vision**.

In [ ]:
# A batch of 8 RGB images, each 64 x 64

batch = np.zeros((8, 64, 64, 3), dtype=np.float32)

print("Shape:", batch.shape)
print("Rank :", batch.ndim)

# 🔤 9. Tensors in NLP

Tensors are also fundamental to Natural Language Processing.

A text sequence can be converted into numerical representations.

For example:

```text
"Hi Amit"
```

may be tokenized into:

```text
["Hi", "Amit"]
```

and mapped to token IDs:

```text
[101, 2057]
```

A collection of sequences forms a higher-dimensional tensor.

### Embeddings

Each token can also be represented by an embedding vector.

Suppose:

```text
"cat" → [0.21, 0.74, 0.12, ...]
```

If we have:

```text
sequence length = 10
embedding size  = 768
```

then one sequence can be represented as:

```text
(10, 768)
```

A batch of 32 sequences becomes:

```text
(32, 10, 768)
```

So tensors are not limited to images.

# 3️⃣ 10. 3D Tensor in NLP — Token Embeddings

For a batch of text:

```text
Batch × Sequence Length × Embedding Dimension
```

Example:

```text
32 × 128 × 768
```

means:

```text
32  → text samples
128 → tokens per sample
768 → embedding values per token
```

This is a **3D tensor**.

### General pattern

```text
Text
 ↓
Tokenization
 ↓
Token IDs
 ↓
Embedding layer
 ↓
3D tensor
 ↓
Transformer / RNN / LSTM
```

This is why tensor concepts are important for understanding modern deep learning architectures.

# 4️⃣ 11. 4D Tensor in Computer Vision

For computer vision, a common batch representation is:

```text
Batch × Height × Width × Channels
```

Example:

```text
64 × 224 × 224 × 3
```

### Channels-first alternative

Some deep-learning frameworks/models use:

```text
Batch × Channels × Height × Width
```

Example:

```text
64 × 3 × 224 × 224
```

### ⚠️ Very important

These are both valid layouts:

```text
NHWC
N = batch
H = height
W = width
C = channels
```

and

```text
NCHW
N = batch
C = channels
H = height
W = width
```

Always check the framework/model's expected input shape.

# 🎥 12. 5D Tensor — Video

A video is a sequence of images (frames).

A single RGB video can commonly be represented as:

```text
Time × Height × Width × Channels
```

Example:

```text
16 × 224 × 224 × 3
```

where:

```text
16  → frames
224 → height
224 → width
3   → RGB channels
```

If we process multiple videos in a batch:

```text
Batch × Time × Height × Width × Channels
```

Example:

```text
8 × 16 × 224 × 224 × 3
```

That is a **5D tensor**.

![5D tensor](assets/5d_tensor.png)

### 🎬 Think of it as

```text
Video
 │
 ├── Frame 1 → 3D image tensor
 ├── Frame 2 → 3D image tensor
 ├── Frame 3 → 3D image tensor
 ├── ...
 └── Frame 16
          │
          ▼
     4D video tensor

Then add batch:
          │
          ▼
     5D batch tensor
```

# 🎞️ 13. Frames Per Second (FPS)

A video is made from a sequence of images shown quickly.

Common frame rates include:

```text
30 FPS → 30 frames / second
60 FPS → 60 frames / second
120 FPS → 120 frames / second
```

For a 10-second video at 30 FPS:

```text
10 × 30 = 300 frames
```

If every frame is:

```text
224 × 224 × 3
```

then the video contains a large amount of numerical data.

### Why tensors?

A tensor gives us a structured representation of this data:

```text
Frames
  ×
Height
  ×
Width
  ×
Channels
```

and a batch adds another axis.

In [ ]:
# Example: 10-second RGB video at 30 FPS
frames = 10 * 30

video = np.zeros((frames, 64, 64, 3), dtype=np.uint8)

print("Number of frames:", frames)
print("Video shape:", video.shape)
print("Video rank:", video.ndim)

# 🧠 14. TensorFlow and Tensors

The notes connect tensors with **ML, DL, and AI models** and identify TensorFlow as a major library.

In TensorFlow:

```python
import tensorflow as tf

x = tf.constant([1, 2, 3])
```

creates a TensorFlow tensor.

### TensorFlow tensor properties

```python
x.shape
x.dtype
```

Example:

```text
Tensor
Shape: (3,)
dtype: int32
```

### NumPy vs TensorFlow

| NumPy | TensorFlow |
|---|---|
| `np.array()` | `tf.constant()` |
| Numerical computing | ML / deep learning framework |
| CPU-focused by default | CPU/GPU/accelerator support |
| Arrays | Tensors + ML operations |
| Scientific computing | Neural-network ecosystem |

In [ ]:
# TensorFlow example
# Uncomment if TensorFlow is installed in your environment.

# import tensorflow as tf

# x = tf.constant([[1, 2], [3, 4]])
# print(x)
# print("Shape:", x.shape)
# print("Rank :", len(x.shape))

# 🔬 15. Tensor Operations

Tensors are useful because mathematical operations can be performed efficiently over many values.

### Element-wise addition

```text
[1, 2, 3]
+
[4, 5, 6]
────────
[5, 7, 9]
```

### Matrix multiplication

For matrices:

```text
A × B = C
```

This is fundamental to neural-network layers.

### Reshaping

A tensor can often be reshaped without changing the number of elements.

Example:

```text
(2, 3)
   ↓
(3, 2)
```

Both contain:

```text
6 elements
```

### ⚠️ Rule

A reshape is possible only when the total number of elements remains the same.

```text
2 × 3 = 6
3 × 2 = 6   ✓
4 × 2 = 8   ✗
```

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])

reshaped = x.reshape(2, 3)

print("Original :", x)
print("Original shape:", x.shape)

print("\nReshaped:")
print(reshaped)
print("New shape:", reshaped.shape)

# 🔄 16. Axis, Shape and Rank — Don't Confuse Them

Consider:

```python
x.shape = (8, 16, 224, 224, 3)
```

### Rank

Number of axes:

```text
rank = 5
```

### Shape

The sizes along each axis:

```text
(8, 16, 224, 224, 3)
```

### Axes

```text
axis 0 → batch
axis 1 → time / frames
axis 2 → height
axis 3 → width
axis 4 → channels
```

### Visual

```text
(8, 16, 224, 224, 3)
 │   │    │    │   │
 │   │    │    │   └── Channels
 │   │    │    └────── Width
 │   │    └─────────── Height
 │   └──────────────── Time
 └──────────────────── Batch
```

> **Exam-ready sentence:** The rank of a tensor is the number of axes, while its shape specifies the number of elements along each axis.

# 🧪 17. Practical Shape Inspection

Whenever you receive ML data, inspect:

```python
data.shape
data.ndim
data.dtype
data.size
```

### Example

```text
(32, 224, 224, 3)
```

Immediately interpret it as:

```text
32 images
224 pixels high
224 pixels wide
3 color channels
```

This habit prevents many ML bugs.

In [ ]:
def inspect_tensor(x, name="Tensor"):
    print(f"{name}")
    print("-" * len(name))
    print("Shape :", x.shape)
    print("Rank  :", x.ndim)
    print("Size  :", x.size)
    print("Dtype :", x.dtype)

sample = np.zeros((32, 224, 224, 3), dtype=np.float32)
inspect_tensor(sample, "Image Batch")

# 🧠 18. Tensors Across ML Domains

| Domain | Typical tensor example |
|---|---|
| Tabular ML | `(samples, features)` |
| Image | `(height, width, channels)` |
| Image batch | `(batch, height, width, channels)` |
| Text embeddings | `(batch, tokens, embedding_dim)` |
| Audio | `(batch, time, channels)` |
| Video | `(time, height, width, channels)` |
| Video batch | `(batch, time, height, width, channels)` |
| Neural-network activations | Depends on layer |

### The key idea

The meaning of each axis depends on the application.

A shape alone is not enough—you must know what each axis represents.

# 🧩 19. Tensor → Deep Learning Model

Tensors are the basic data containers passed between layers.

```text
Input Tensor
     │
     ▼
┌───────────────┐
│ Neural Layer  │
└───────┬───────┘
        ▼
Activation Tensor
        │
        ▼
┌───────────────┐
│ Neural Layer  │
└───────┬───────┘
        ▼
Output Tensor
```

### CNN example

```text
Image Tensor
(224,224,3)
      ↓
Convolution
      ↓
Feature Maps
      ↓
Pooling
      ↓
More Feature Maps
      ↓
Flatten / Global Pool
      ↓
Dense Layer
      ↓
Prediction
```

### RNN / LSTM example

```text
Sequence Tensor
      ↓
RNN / LSTM
      ↓
Hidden-state tensors
      ↓
Output
```

### Transformer / NLP example

```text
Token IDs
   ↓
Embeddings
   ↓
3D tensor
(batch × tokens × embedding)
   ↓
Transformer blocks
   ↓
Output
```

# 💡 20. Why Tensors Are So Important

### Without tensors

We would have to manage individual values, matrices, images, frames, and batches separately.

### With tensors

The same mathematical abstraction works across:

```text
Numbers
  ↓
Vectors
  ↓
Matrices
  ↓
Images
  ↓
Batches
  ↓
Videos
  ↓
Neural-network activations
```

This common representation is one reason tensors are fundamental to modern deep learning.

---

<div style="padding:18px;border-radius:14px;border:2px solid #2a9d8f">

### ⭐ One-line definition

**A tensor is a multidimensional numerical array used to represent and process structured data in machine learning and deep learning.**

</div>

# 📝 21. Exam-Ready Notes

## Define Tensor

> A tensor is a multidimensional array of numerical values used as a fundamental data structure for representing and processing data in machine learning and deep learning.

## What is a 0D tensor?

> A 0D tensor is a scalar containing a single value, such as `7`. Its shape is `()`.

## What is a 1D tensor?

> A 1D tensor is a vector containing values along one axis, such as `[1,2,3,4]`.

## What is a 2D tensor?

> A 2D tensor is a matrix arranged using rows and columns.

## What is a 3D tensor?

> A 3D tensor contains data along three axes. An RGB image is commonly represented as height × width × channels.

## What is a 4D tensor?

> A 4D tensor commonly represents a batch of images, such as batch × height × width × channels.

## What is a 5D tensor?

> A 5D tensor can represent a batch of videos, commonly as batch × time × height × width × channels.

## Why are tensors used in deep learning?

> Tensors provide a consistent multidimensional numerical representation that can be efficiently processed by neural-network operations on CPUs, GPUs, and other accelerators.

# 🎯 22. Final Revision Map

```text
                         TENSORS
                            │
          ┌─────────────────┼─────────────────┐
          │                 │                 │
        0D                1D                2D
      Scalar            Vector             Matrix
        │                 │                 │
        └─────────────────┼─────────────────┘
                          │
                          ▼
                         3D
                  Image / Volume
                          │
                          ▼
                         4D
                    Batch of Images
                          │
                          ▼
                         5D
                     Video Batch
                          │
                          ▼
                DEEP LEARNING MODELS
             ┌────────────┼────────────┐
             │            │            │
            CNN          RNN         LSTM
             │            │            │
             └────────────┼────────────┘
                          ▼
                     TENSORFLOW
```

### 🧠 Super-short memory trick

```text
0D = one value
1D = list
2D = table
3D = image / stack
4D = batch of images
5D = batch of videos
```

### 🚀 Final takeaway

**ML data → Tensor → Model → Tensor operations → Prediction**

Tensors are the common numerical language connecting **data, computer vision, NLP, and deep learning models**.